#netstat -anp|grep 8081
#kill -9 18462
#nohup java -jar mail.jar &
#tail nohup.out
#cp /dev/null nohup.out
#cat /dev/null > nohup.out
server:
  port: 8081
  tomcat:
    max-http-header-size: 8096

spring:
  mail:
    host: smtp.qq.com
    username: 517317384@qq.com
    password: rfufgihobsumcafj
    port: 465
    properties: {
      mail.smtp.auth: 'true',
      mail.smtp.timeout: '25000',
      mail.smtp.port: '465',
      mail.smtp.socketFactory.port: '465',
      mail.smtp.socketFactory.fallback: 'false',
      mail.smtp.socketFactory.class: 'javax.net.ssl.SSLSocketFactory'
    }
  freemarker:
    cache: true
    request-context-attribute: request
    suffix: .html

mail:
  smtp:
#    img: C:\Users\user\Pictures\image\
    img: /opt/download/


scheduled:
  cron: 0 0 8 * * ?
#  cron: 0/5 * * * * ?
enable:
  scheduled: true


customize:
  userinfolist[0]:
    name: '孤峰'
    receiver: '954649451@qq.com'
    citycode: '101220101'
    consname: 'tiancheng'
  userinfolist[1]:
    name: 'wo'
    receiver: '517317384@qq.com'
    citycode: '101010100'
    consname: 'mojie'
#  userinfolist[2]:
#    name: 'ppf'
#    receiver: '609959462@qq.com'
#    citycode: '101030100'
#    consname: 'chunv'
#  userinfolist[3]:
#    name: '曹爷'
#    receiver: '351864319@qq.com'
#    citycode: '101100101'
#    consname: 'jinniu'
#  userinfolist[4]:
#    name: '彤彤'
#    receiver: '1020834358@qq.com'
#    citycode: '101090101'
#    consname: 'sheshou'



